### ISSUE TITLE
Suggestion to change / generalize integration test configuration file

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/simtools#1385]
I would like to suggest a change to the integration test configuration files to generalize its usage to setting workflows. This would allow to use a single metaschema for validation (and allows good to re-use methods).

The suggestion is to add one additional layer of hierarchy, meaning that e.g.,

```
CTA_SIMPIPE:
  APPLICATION: simtools-submit-data-from-external
  TEST_NAME: submit_table
  CONFIGURATION:
    INPUT_META: ./tests/resources/MLTdata-preproduction.meta.yml
    INPUT: ./tests/resources/MLTdata-preproduction.ecsv
    SCHEMA: ./src/simtools/schemas/input/MST_mirror_2f_measurements.schema.yml
    OUTPUT_PATH: simtools-output
    OUTPUT_FILE: test.ecsv
  INTEGRATION_TESTS:
    - OUTPUT_FILE: test.ecsv
```

becomes

```
CTA_SIMPIPE:
  APPLICATIONS:
      - APPLICATION: simtools-submit-data-from-external
        TEST_NAME: submit_table
        CONFIGURATION:
          INPUT_META: ./tests/resources/MLTdata-preproduction.meta.yml
          INPUT: ./tests/resources/MLTdata-preproduction.ecsv
          SCHEMA: ./src/simtools/schemas/input/MST_mirror_2f_measurements.schema.yml
          OUTPUT_PATH: simtools-output
          OUTPUT_FILE: test.ecsv
        INTEGRATION_TESTS:
          - OUTPUT_FILE: test.ecsv
```

What I suggest is to add a `APPLICATIONS` keyword, and then have a list of `APPLICATION`s. For the integration tests, this will continue to be a single application. For setting workflows, we can have e.g. a data validation, derivation, and then plotting workflow configured in one single file.

Any objections / suggestions?
