### ISSUE TITLE
Pedestal and internal laser calibration simulations

### ISSUE THREAD

**Issue by orelgueta** [gammasim/simtools#1622]
Following a request from the LST team, the possibility to simulate pedestal events starts to be needed. Can we add that functionality to simtools? In terms of priority, we should start from pedestal simulations. Adding the internal laser events is quite easy afterwards since it does not require the LightEmission package.

As an example, attached is the bash script used at the moment to simulate that using sim_telarray.

[run_calibration.sh.txt](https://github.com/user-attachments/files/20980039/run_calibration.sh.txt)

**Comment by orelgueta** [comment]
> * is it sufficient to have a new application `simulate_calibration_events`? I would prefer to separate it clearly into a `simulate_pedestal_events` and `simulate_laser_events` application.

At the moment CalibPipe asked for two separate files, so having two separate applications would be fine. However, simulating pedestal events can be done at the beginning for any simulation run (Cherenkov or calibration), so I think both options should be made available. That is, one application which is a "pure" `simulate_pedestal_events` and having a command line argument for the `simulate_laser_events` application that adds pedestal events with the command line argument to sim_telarray. Whether we should add the same for the Cherenkov simulations can be discussed (but would be easy to add, so why not).

> * for the laser events: any idea for a better name? These are not always lasers. `simulate_calibration_flashes` or `simulate_optical_pulses` or `simulate_flatfielding_events`?

The name is taken directly from the sim_telarray parameter name. In the future I think we might not use this functionality at all, so maybe the name is not very important. However, if I have to choose one now I would go for `simulate_sim_telarray_calibration_flashes` to make sure it's clear that it's the internal one.

> * otherwise the applications are following the implementation of e.g. `simulate_light_emission.py`

Light emission is different in the sense that it uses the LightEmission package (which is the next step to implement).


> What are the configurable parameters for the pedestal generator?
> 
> * number of calibration events `--n_events`

Yes

> * do we need the nsb scaling / asum parameters and the HALFMOON/NSB_AUTOSCALE settings? Or is this covered by the selected model_version?\

I think nsb scaling is useful to have. It allows to create many different levels with the same model. The rest should be covered by the model_version. We can discuss it though of course.

> * I guess due to NSB_AUTOSCALE, we need to set theta/phi?\

Indeed (also useful for simulating a specific source).

> * `star_field_file` pointing to replace `C stars=${workdir}/star_field.txt`

Stars are a discussion point. One can imagine that the star file is produced in the application by providing the name of the source and time of year or something like that. At the moment it can be just an option to provide a file though (or ignored for the first version).

**Comment by GernotMaier** [comment]
These are the options I think the new application to simulate pedestal events requires. Please edit directly to keep it clearer.

```
applications:
- application: simtools-pedestal-events
  configuration:
    telescope: LSTN-03
    azimuth_angle: North # Needed as NSB might be elevation dependent
    zenith_angle: 20  # Needed as NSB might be elevation dependent
    n_events: 1000
    data_directory: simtools-data
    label: test-production-North
    log_level: DEBUG
    model_version: 6.0.0
    output_path: simtools-output
    pack_for_grid_register: simtools-grid-output
    run_number: 10
    simulation_software: corsika_sim_telarray
    site: North
    # stars a user-provided text file for now?
    stars: star_field.txt
    nsb_scaling_factor: None   # None == use 1.
    asum_threshold: None  # None == use threshold from model parameters
```

Parameters used by `simulate_prod` but removed for pedestal events:

```
core_scatter: 10 500 m
energy_range: 100 GeV 1 TeV
eslope: -2.0
view_cone: 0 deg 0 deg
nshow: 5   # replaced by n_events
primary: gamma
sim_telarray_random_instrument_instances: 100  # not needed, as we simulate on run only
array_layout_name: test_layout # simulate per telescope?
```

@orelgueta -  why do we need `-DHALFMOON`? What is set by this flag? Threshold and NSB are already set through the configuration, is there something else? Where would we set the moon NSB spectrum?
