### ISSUE TITLE
pyyaml dumps non-standard yaml

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/simtools#251]
Really not a big issue, but something not to forget.

pyyaml does not follow the newest yaml standard (1.2) and seems to be depreciated. Alternatively, [ruamel.yaml](https://yaml.readthedocs.io/en/latest/) could be used, which is a derivative of the pyyaml we are using right now.

One point where it gets important.

The following list:
```
  ASSOCIATION:
    - SITE: South
      CLASS: MST
      TYPE: FlashCam
      SUBTYPE: D
      ID: MSTS
    - SITE: North
      CLASS: MST
      TYPE: NectarCam
      SUBTYPE: D
      ID: MSTN
```
is dumped incorrectly with pyyaml to
```
    ASSOCIATION:
    - SITE: South
      CLASS: MST
      TYPE: FlashCam
      SUBTYPE: D
      ID: South-MST-FlashCam-D
    - SITE: North
      CLASS: MST
      TYPE: NectarCam
      SUBTYPE: D
      ID: North-MST-NectarCam-D
```

ruaml.yaml can do this correctly when using the flag `offset=2`
