### ISSUE TITLE
Improve linting of different file types - consider using super linter

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/simtools#674]
We have a variety of different file types in simtools and not all are of a linting process right now.

File types: py, yaml, docker, github action, markdown, rst, ...

[Super-linter](https://github.com/marketplace/actions/super-linter) is a nice wrapper for many linter types and allows in a single and simple github action workflow to lint a large number of different file types. 

I suggest to add this as CI workflow. Any opinions / objections?

The github action step is then simply:

```
      - name: Lint Code Base
        uses: super-linter/super-linter@v5
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_ENV: true
          VALIDATE_YAML: true
          VALIDATE_PYTHON_ISORT: true
          VALIDATE_PYTHON_FLAKE8: true
          VALIDATE_PYTHON_BLACK: true
          VALIDATE_MARKDOWN: true
          VALIDATE_DOCKERFILE_HADOLINT: true
          LINTER_RULES_PATH: ./
          PYTHON_BLACK_CONFIG_FILE: pyproject.toml
          PYTHON_ISORT_CONFIG_FILE: pyproject.toml

          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Unfortunately, I couldn't find a good rst linter.
