### ISSUE TITLE
Reading of yaml files and usage of astropy constructors

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/simtools#812]
We usually use `astropy.io.misc.yaml` to read yaml files. 

This has the disadvantage that it is much slower to import (numbers on my local computer):

- 396388    astropy.io.misc.yaml
- 32077   yaml

These are us, so we are talking about a factor of 12! This is roughly 1/3 of the import time of general.py.

Question: do we actual use the yaml constructors for astropy anywhere? My feeling is that they are nice, but not needed.

That you don't have to search - here an example, everything starting with `!`:

```
enith_angle:
  len: 1
  unit: !astropy.units.Unit {unit: deg}
  default: !astropy.units.Quantity
    value: 20
    unit: !astropy.units.Unit {unit: deg}
  names: ['zenith', 'theta']
azimuth_angle:
  len: 1
  unit: !astropy.units.Unit {unit: deg}
  default: !astropy.units.Quantity
    value: 0
    unit: !astropy.units.Unit {unit: deg}
  names: ['azimuth', 'phi']
nsb_spectrum:
  len: 1
  unit: null
  default: null
```

I suggest to remove those constructors and use plain yaml. Please protest if you don't agree.
